#!/bin/bash
echo   ""
perl passwordvalidator.pl "asd^&*J8i#1Yjk5Iytysdk.~\`^\,;@"
echo   ""
perl passwordvalidator.pl "asd^&*J8i#1Yjk5Iytya& "
echo   ""
perl passwordvalidator.pl "asd^&*J8i#1Yjk5Iyta"
echo   ""
perl passwordvalidator.pl "asd^&*J8i#1Yjk5Iyt7"
echo    ""
perl passwordvalidator.pl "asd^&*J8i#1Yjk5Iyt*"
echo   ""
perl passwordvalidator.pl "asd^&*J8i#1Yjk5"
echo   ""
perl passwordvalidator.pl "asd^&*J8i#1Yjka"
echo   ""
perl passwordvalidator.pl "asd^&*J8i#1Yj^H"
echo   ""
perl passwordvalidator.pl "asd^&*J8i#"
echo   ""
perl passwordvalidator.pl "asd^&*"
echo   ""
